# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-03e4dce8-69c9-4690-8ef3-c5dbf1ee0c4e";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-03e4dce8-69c9-4690-8ef3-c5dbf1ee0c4e".device = "/dev/disk/by-uuid/03e4dce8-69c9-4690-8ef3-c5dbf1ee0c4e";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-03e4dce8-69c9-4690-8ef3-c5dbf1ee0c4e";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-03e4dce8-69c9-4690-8ef3-c5dbf1ee0c4e";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4776-E953";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
